name: Update NuGet

on:
  push:
    branches:
      - "main"

jobs:
  build:
    env:
      BUILD_CONFIG: 'Release'
      OUT_FOLDER: './out'
      NUGET_TOKEN: ${{ secrets.NUGET_BLEND_SITEMAP_TOKEN }}

    runs-on: windows-latest
    strategy:
      matrix: 
        dotnet-versions: ['6.0']

    name: Update_NuGet
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET Core SDK ${{matrix.dotnet-versions}}
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: ${{matrix.dotnet-versions}}

      - name: Setup NuGet.exe
        uses: nuget/setup-nuget@v1        
        with:
          nuget-version: latest

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: patch
      
      - name: Install dependencies
        run: dotnet restore

      - name: Build Blend.Sitemap
        run: dotnet pack .\Our.Umbraco.Blend.Sitemap\Our.Umbraco.Blend.Sitemap.csproj --no-restore -c ${{ env.BUILD_CONFIG }} -o ${{ env.OUT_FOLDER }}  /p:ContinuousIntegrationBuild=true,version=${{ steps.bump-semver.outputs.new_version }}

      - name: Publish Nuget to Nuget.org
        run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey $env:NUGET_TOKEN

      

      - uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ steps.bump-semver.outputs.new_version }}
          message: '${{ steps.bump-semver.outputs.new_version }}: PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}'